[package]
name = "slow-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
sha2 = "0.10"
sysinfo = "0.38.1"
serde = { version = "1.0", features = ["derive"] }
clap = { version = "4.5.58", features = ["derive"] }
chrono = "0.4"
csv = "1.3"
ratatui = "0.30"
crossterm = "0.29"
libc = "0.2.182"
